version: 1.0.0-sdiz

signing:
  debug:
    store: $MOD_HOME/res/my-release-key.keystore
    pass: 123456
    alias: alias_name

  release:
    store: $MOD_HOME/res/my-release-key.keystore
    pass: 123456
    alias: alias_name

maps_key:
  debug: AIzaSyAfkzgbeulesz-SSnWNsVvqEty6wdOCNPk
  release: AIzaSyAfkzgbeulesz-SSnWNsVvqEty6wdOCNPk
